<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="15.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <Configuration Condition="'$(Configuration)' == ''">Release</Configuration>
    <Platform Condition="'$(Platform)' == ''">AnyCPU</Platform>
    <OutputType>WinExe</OutputType><RootNamespace>NLNS</RootNamespace><AssemblyName>NLNS</AssemblyName>
    <TargetFrameworkVersion>v4.8</TargetFrameworkVersion><OutputPath>..\bin\$(Configuration)\</OutputPath>
    <ApplicationIcon>..\assets\nlns.ico</ApplicationIcon><ApplicationManifest>app.manifest</ApplicationManifest>
    <Optimize>true</Optimize><Prefer32Bit>false</Prefer32Bit>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="System"/><Reference Include="System.Core"/><Reference Include="System.Drawing"/>
    <Reference Include="System.Windows.Forms"/><Reference Include="System.Web.Extensions"/>
    <Compile Include="AssemblyInfo.cs"/><Compile Include="Engine.cs"/><Compile Include="MainForm.cs"/><Compile Include="Program.cs"/>
  </ItemGroup>
  <Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets"/>
</Project>
